### PR TITLE
feat: adding config clang-format

### PR DESCRIPTION
**Pull request by kayabaakihiko13**
in this push is adding config clang-format in Cpp Language.

this for documentation:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html

### CODE REVIEW

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
I am not pulling this commit. For C and C++, please follow the Linux kernel coding style.

See: https://github.com/torvalds/linux/blob/master/.clang-format

You can adjust several entries I mention below:
```
IndentWidth: 8
TabWidth: 8
UseTab: Always
IndentCaseLabels: false
```

**Comment by kayabaakihiko13** [comment]
> I am not pulling this commit. For C and C++, please follow the Linux kernel coding style.
> 
> See: https://github.com/torvalds/linux/blob/master/.clang-format
> 
> You can adjust several entries I mention below:
> 
> ```
> IndentWidth: 8
> TabWidth: 8
> UseTab: Always
> IndentCaseLabels: false
> ```

okey, i fix this issue.
anyways for 
> ...
> BasedOnStyle: LLVM
keep or remove it ?

**Comment by ammarfaizi2** [comment]
> BasedOnStyle: LLVM

I missed it; yes, remove it.

**Comment by kayabaakihiko13** [comment]
> > BasedOnStyle: LLVM
> 
> I missed it; yes, remove it.

> okey done sir !
> any have issue for this PR?

**Review by ammarfaizi2 — APPROVED** [review]

**Pull request merged**
